import subprocess
import os
import shutil
import pytest
from pathlib import Path

# Paths
WORKSPACE_ROOT = Path(__file__).parent.parent
RUST_DIR = WORKSPACE_ROOT / "rust" / "kernels"
PTX_DIR = RUST_DIR / "ptx"
COMPILE_PY = WORKSPACE_ROOT / "compile_kernels.py"
COMPILE_SH = RUST_DIR / "compile_kernels.sh"

def clean_ptx():
    """Remove all PTX files"""
    if PTX_DIR.exists():
        shutil.rmtree(PTX_DIR)
    PTX_DIR.mkdir(parents=True, exist_ok=True)

def get_ptx_files():
    """Get list of PTX files and their sizes"""
    if not PTX_DIR.exists():
        return {}
    return {f.name: f.stat().st_size for f in PTX_DIR.glob("*.ptx")}

@pytest.mark.skipif(shutil.which("nvcc") is None, reason="NVCC not available")
def test_compilation_consistency():
    """
    Verify that compile_kernels.py and compile_kernels.sh produce 
    the same set of PTX files.
    """
    # 1. Compile with Python script
    print("\n--- Running Python compilation ---")
    clean_ptx()
    
    # Run python script
    result_py = subprocess.run(
        ["python3", str(COMPILE_PY)], 
        cwd=WORKSPACE_ROOT,
        capture_output=True,
        text=True
    )
    
    # Python script should succeed
    if result_py.returncode != 0:
        print("Python script failed:")
        print(result_py.stderr)
    assert result_py.returncode == 0, "compile_kernels.py failed"
    
    py_files = get_ptx_files()
    assert len(py_files) > 0, "No PTX files generated by Python script"
    
    # 2. Compile with Bash script
    print("\n--- Running Bash compilation ---")
    clean_ptx()
    
    # Run bash script
    result_sh = subprocess.run(
        ["bash", str(COMPILE_SH)],
        cwd=RUST_DIR, # Script expects to be run from its dir or handles it? 
                      # Script has `cd "$SCRIPT_DIR"` so it should be fine.
        capture_output=True,
        text=True
    )
    
    # Bash script should succeed
    if result_sh.returncode != 0:
        print("Bash script failed:")
        print(result_sh.stderr)
    assert result_sh.returncode == 0, "compile_kernels.sh failed"
    
    sh_files = get_ptx_files()
    assert len(sh_files) > 0, "No PTX files generated by Bash script"

    # 3. Compare results
    print("\n--- Comparing results ---")
    
    # Check that filenames match exactly
    py_names = set(py_files.keys())
    sh_names = set(sh_files.keys())
    
    missing_in_sh = py_names - sh_names
    missing_in_py = sh_names - py_names
    
    assert not missing_in_sh, f"Files in Python but not Bash: {missing_in_sh}"
    assert not missing_in_py, f"Files in Bash but not Python: {missing_in_py}"
    
    # Check specifically for the new kernels
    expected_kernels = ["conv_ops", "winding_ops"]
    architectures = ["75", "80", "86", "90"]
    
    for kernel in expected_kernels:
        for arch in architectures:
            filename = f"{kernel}_sm{arch}.ptx"
            assert filename in py_names, f"New kernel {filename} missing from compilation"

    print("SUCCESS: Python and Bash scripts produce identical kernel sets")

if __name__ == "__main__":
    test_compilation_consistency()
