"""Core module for Syntonic."""

from syntonic.core.state import State, state
from syntonic.core.dtype import (
    DType,
    float32,
    float64,
    complex64,
    complex128,
    int32,
    int64,
    winding,
    get_dtype,
    promote_dtypes,
)
from syntonic.core.device import (
    Device,
    cpu,
    cuda,
    device,
)
from syntonic._core import (
    TensorStorage, 
    cuda_is_available, 
    cuda_device_count,
    # Linear algebra functions
    linalg_mm, linalg_mm_add,
    linalg_mm_tn, linalg_mm_nt, linalg_mm_tt,
    linalg_mm_hn, linalg_mm_nh,
    linalg_bmm,
    linalg_mm_phi, linalg_phi_bracket, linalg_phi_antibracket,
    linalg_mm_corrected, linalg_mm_golden_phase, linalg_mm_golden_weighted,
    linalg_projection_sum,
    Structure,
    # Exact arithmetic
    Rational,
    GoldenExact,
    FundamentalConstant,
    CorrectionLevel,
    SymExpr,
    srt_phi,
    srt_phi_inv,
    srt_q_deficit,
    srt_structure_dimension,
    srt_correction_factor,
    # Hypercomplex
    Quaternion,
    Octonion,
    # Winding
    WindingState,
    WindingStateIterator,
    enumerate_windings,
    enumerate_windings_by_norm,
    enumerate_windings_exact_norm,
    count_windings,
    # Spectral
    theta_series_evaluate,
    theta_series_weighted,
    theta_series_derivative,
    heat_kernel_trace,
    heat_kernel_weighted,
    heat_kernel_derivative,
    compute_eigenvalues,
    compute_golden_weights,
    compute_norm_squared,
    spectral_zeta,
    spectral_zeta_weighted,
    partition_function,
    theta_sum_combined,
    count_by_generation,
    filter_by_generation,
    knot_eigenvalue,
    compute_knot_eigenvalues,
    knot_heat_kernel_trace,
    knot_spectral_zeta,
    knot_spectral_zeta_complex,
)

__all__ = [
    # State
    'State',
    'state',
    # DTypes
    'DType',
    'float32',
    'float64',
    'complex64',
    'complex128',
    'int32',
    'int64',
    'winding',
    'get_dtype',
    'promote_dtypes',
    # Devices
    'Device',
    'cpu',
    'cuda',
    'cuda_is_available',
    'cuda_device_count',
    'device',
    # Rust backend
    'TensorStorage',
    # Linear algebra functions
    'linalg_mm', 'linalg_mm_add',
    'linalg_mm_tn', 'linalg_mm_nt', 'linalg_mm_tt',
    'linalg_mm_hn', 'linalg_mm_nh',
    'linalg_bmm',
    'linalg_mm_phi', 'linalg_phi_bracket', 'linalg_phi_antibracket',
    'linalg_mm_corrected', 'linalg_mm_golden_phase', 'linalg_mm_golden_weighted',
    'linalg_projection_sum',
    'Structure',
    # Exact arithmetic
    'Rational',
    'GoldenExact',
    'FundamentalConstant',
    'CorrectionLevel',
    'SymExpr',
    'srt_phi',
    'srt_phi_inv',
    'srt_q_deficit',
    'srt_structure_dimension',
    'srt_correction_factor',
    # Hypercomplex
    'Quaternion',
    'Octonion',
    # Winding
    'WindingState',
    'WindingStateIterator',
    'enumerate_windings',
    'enumerate_windings_by_norm',
    'enumerate_windings_exact_norm',
    'count_windings',
    # Spectral
    'theta_series_evaluate',
    'theta_series_weighted',
    'theta_series_derivative',
    'heat_kernel_trace',
    'heat_kernel_weighted',
    'heat_kernel_derivative',
    'compute_eigenvalues',
    'compute_golden_weights',
    'compute_norm_squared',
    'spectral_zeta',
    'spectral_zeta_weighted',
    'partition_function',
    'theta_sum_combined',
    'count_by_generation',
    'filter_by_generation',
    'knot_eigenvalue',
    'compute_knot_eigenvalues',
    'knot_heat_kernel_trace',
    'knot_spectral_zeta',
    'knot_spectral_zeta_complex',
]
